package dev.keiji.openpgp.packet

import dev.keiji.openpgp.PublicKeyAlgorithm
import dev.keiji.openpgp.packet.pkesk.EncryptedSessionKey
import dev.keiji.openpgp.packet.pkesk.PacketPublicKeyEncryptedSessionKeyV3
import dev.keiji.openpgp.packet.pkesk.PacketPublicKeyEncryptedSessionKeyV6
import dev.keiji.openpgp.toHex
import org.junit.jupiter.api.Assertions.assertArrayEquals
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream

class PacketDecoderPkeskTest {

    @Test
    fun decodePkeskV6X25519Test() {
        // RFC 9580 Appendix A.8.1.
        val packetList = PacketDecoder.decode(Rfc9580TestVectors.PKESK_V6_X25519)
        assertEquals(1, packetList.size)

        val pkesk = packetList[0]
        assertEquals(Tag.PublicKeyEncryptedSessionKey, pkesk.tag)
        assertTrue(pkesk is PacketPublicKeyEncryptedSessionKeyV6)
        if (pkesk is PacketPublicKeyEncryptedSessionKeyV6) {
            assertEquals(6, pkesk.version)
            assertEquals(6, pkesk.keyVersion)
            assertEquals(
                "12:C8:3F:1E:70:6F:63:08:FE:15:1A:41:77:43:A1:F0:33:79:0E:93:E9:97:84:88:D1:DB:37:8D:A9:93:08:85",
                pkesk.fingerprint?.toHex(":")
            )
            assertEquals(PublicKeyAlgorithm.X25519, pkesk.publicKeyAlgorithm)

            val encryptedSessionKey = pkesk.encryptedSessionKey
            assertTrue(encryptedSessionKey is EncryptedSessionKey.X25519)
            if (encryptedSessionKey is EncryptedSessionKey.X25519) {
                assertEquals(
                    "87:CF:18:D5:F1:B5:3F:81:7C:CE:5A:00:4C:F3:93:CC:89:58:BD:DC:06:5F:25:F8:4A:F5:09:B1:7D:D3:67:64",
                    encryptedSessionKey.ephemeralPublicKey?.toHex(":")
                )
                assertEquals(
                    0x18,
                    encryptedSessionKey.encryptedSessionKey?.size
                )
            }
        }
    }

    @Test
    fun encodePkeskV6RoundTripTest() {
        val expected = Rfc9580TestVectors.PKESK_V6_X25519

        val packetList = PacketDecoder.decode(expected)
        val actual = ByteArrayOutputStream().let {
            packetList[0].writeTo(false, it)
            it.toByteArray()
        }

        assertArrayEquals(expected, actual)
    }

    @Test
    fun decodePkeskV3RsaTest() {
        // Generated by gpg: RSA-encrypted session key.
        val file = encryptedFixtureOf("rsa3072")
        val packetList = PacketDecoder.decode(file.readBytes())
        assertEquals(2, packetList.size)

        val pkesk = packetList[0]
        assertEquals(Tag.PublicKeyEncryptedSessionKey, pkesk.tag)
        assertTrue(pkesk is PacketPublicKeyEncryptedSessionKeyV3)
        if (pkesk is PacketPublicKeyEncryptedSessionKeyV3) {
            assertEquals(3, pkesk.version)
            assertEquals(PublicKeyAlgorithm.RSA_ENCRYPT_OR_SIGN, pkesk.publicKeyAlgorithm)
            assertEquals(8, pkesk.keyId.size)
            assertTrue(pkesk.encryptedSessionKey is EncryptedSessionKey.Rsa)
        }
    }

    @Test
    fun decodePkeskV3EcdhTest() {
        // Generated by gpg: ECDH-encrypted session key
        // (nistp256 encryption subkey).
        val file = encryptedFixtureOf("ecdsa_p256")
        val packetList = PacketDecoder.decode(file.readBytes())
        assertEquals(2, packetList.size)

        val pkesk = packetList[0]
        assertTrue(pkesk is PacketPublicKeyEncryptedSessionKeyV3)
        if (pkesk is PacketPublicKeyEncryptedSessionKeyV3) {
            assertEquals(3, pkesk.version)
            assertEquals(PublicKeyAlgorithm.ECDH, pkesk.publicKeyAlgorithm)
            assertTrue(pkesk.encryptedSessionKey is EncryptedSessionKey.Ecdh)
        }
    }

    @Test
    fun encodePkeskV3RoundTripTest() {
        val fixtureDir = java.io.File("src/test/resources/gpg")
        val files = fixtureDir.listFiles { f -> f.name.endsWith("_hello_txt_encrypted.gpg") }
            ?: return
        assertTrue(files.isNotEmpty())
        files.sortedBy { it.name }.forEach { file ->
            val expected = file.readBytes()
            val packetList = PacketDecoder.decode(expected)
            val actual = ByteArrayOutputStream().let {
                PacketEncoder.encode(packetList, it)
                it.toByteArray()
            }

            assertArrayEquals(expected, actual, "round-trip failed for ${file.name}")
        }
    }

    private fun encryptedFixtureOf(keyInfix: String): java.io.File {
        // The message fixtures are named after the Key ID of the
        // signing key, so resolve the Key ID from the corresponding
        // public key fixture first.
        val fixtureDir = java.io.File("src/test/resources/gpg")
        val publicKeyFile = fixtureDir.listFiles { f ->
            f.name.endsWith("_${keyInfix}_publickey.gpg")
        }?.firstOrNull() ?: return java.io.File(fixtureDir, "NOT_FOUND")

        val keyId = publicKeyFile.name.substringBefore('_')
        return java.io.File(fixtureDir, "${keyId}_hello_txt_encrypted.gpg")
    }
}
