package dev.keiji.openpgp.packet

import dev.keiji.openpgp.PublicKeyAlgorithm
import dev.keiji.openpgp.toHex
import dev.keiji.openpgp.packet.publickey.PacketPublicKey
import dev.keiji.openpgp.packet.publickey.PacketPublicKeyV4
import dev.keiji.openpgp.packet.publickey.keyId
import dev.keiji.openpgp.packet.secretkey.PacketSecretKeyV4
import dev.keiji.openpgp.packet.secretkey.s2k.SecretKeyEncryptionType
import dev.keiji.openpgp.packet.signature.PacketSignatureV4
import org.junit.jupiter.api.Assertions.assertArrayEquals
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.io.ByteArrayOutputStream
import java.io.File

/**
 * Decode-and-re-encode verification against fixtures generated by gpg
 * (see tools/gpg-generate-fixtures.sh). Every fixture is re-encoded
 * after decoding and must be byte-identical.
 *
 * Fixtures are regenerated with fresh keys, so the gpg-reported Key ID
 * of each key differs between runs. The Key ID is carried by the
 * fixture file name (as the low-order 64 bits of the version 4
 * fingerprint) and serves as ground truth for the fingerprint
 * calculation; the tests enumerate fixtures by their name pattern
 * instead of hard-coding key IDs.
 */
class PacketDecoderGpgFixtureTest {
    private val fixtureDir = File("src/test/resources/gpg")

    private fun fixtures(suffix: String): List<File> {
        val files = fixtureDir.listFiles { file -> file.name.endsWith(suffix) }
            ?: return emptyList()
        return files.sortedBy { it.name }
    }

    private fun singleFixture(infix: String, suffix: String): File {
        return fixtures(suffix).first { it.name.contains(infix) }
    }

    private fun messageFixtureOf(keyInfix: String, kind: String): File {
        // Message fixtures are named after the Key ID of the signing
        // key, so resolve the Key ID from the public key fixture.
        val publicKeyFile = fixtures("_${keyInfix}_publickey.gpg").first()
        val keyId = publicKeyFile.name.substringBefore('_')
        return File(fixtureDir, "${keyId}_hello_txt_$kind")
    }

    private fun assertRoundTrip(file: File) {
        val expected: ByteArray
        if (file.name.endsWith("_armored.gpg")) {
            // For armored fixtures, compare against the dearmored
            // binary packet sequence.
            val pgpData = dev.keiji.openpgp.PgpData.loadAsciiArmored(file)
            expected = pgpData.blockList.firstOrNull()?.data ?: ByteArray(0)
        } else {
            expected = file.readBytes()
        }

        val packetList = PacketDecoder.decode(expected)
        val actual = ByteArrayOutputStream().let {
            PacketEncoder.encode(packetList, it)
            it.toByteArray()
        }
        assertArrayEquals(expected, actual, "round-trip failed for ${file.name}")
    }

    @Test
    fun keyRoundTripTest() {
        val files = fixtures("_publickey.gpg") +
                fixtures("_publickey_armored.gpg") +
                fixtures("_secretkey.gpg")
        assertTrue(files.isNotEmpty())
        files.forEach { assertRoundTrip(it) }
    }

    @Test
    fun messageRoundTripTest() {
        val files = fixtures("_hello_txt_signed.gpg") +
                fixtures("_hello_txt_detached.sig") +
                fixtures("_hello_txt_encrypted.gpg") +
                fixtures("hello_txt_clearsigned_by_") +
                listOf(File(fixtureDir, "hello_txt_symmetric_encrypted.gpg"))
        assertTrue(files.isNotEmpty())
        files.forEach { assertRoundTrip(it) }
    }

    @Test
    fun keyIdOfFixturesTest() {
        // The file name of each fixture carries the gpg-reported Key ID
        // of the primary key as its first 16 hexadecimal digits.
        val files = fixtures("_publickey.gpg")
        assertTrue(files.isNotEmpty())
        files.forEach { file ->
            val expectedKeyIdHex = file.name.substringBefore('_')
            assertEquals(16, expectedKeyIdHex.length)

            val packetList = PacketDecoder.decode(file.readBytes())
            val primaryKeyPacket = packetList.filterIsInstance<PacketPublicKey>().first()

            assertEquals(4, primaryKeyPacket.version)
            assertEquals(expectedKeyIdHex, primaryKeyPacket.keyId().toHex(""))
        }
    }

    @Test
    fun algorithmMatrixTest() {
        val expectedAlgorithmsByInfix = mapOf(
            "rsa3072" to listOf(
                PublicKeyAlgorithm.RSA_ENCRYPT_OR_SIGN,
                PublicKeyAlgorithm.RSA_ENCRYPT_OR_SIGN,
            ),
            "rsa4096" to listOf(
                PublicKeyAlgorithm.RSA_ENCRYPT_OR_SIGN,
                PublicKeyAlgorithm.RSA_ENCRYPT_OR_SIGN,
            ),
            "ed25519" to listOf(
                PublicKeyAlgorithm.EDDSA_LEGACY,
                PublicKeyAlgorithm.ECDH,
            ),
            "ecdsa_p256" to listOf(
                PublicKeyAlgorithm.ECDSA,
                PublicKeyAlgorithm.ECDH,
            ),
            "ecdsa_bp256" to listOf(
                PublicKeyAlgorithm.ECDSA,
                PublicKeyAlgorithm.ECDH,
            ),
        )
        expectedAlgorithmsByInfix.forEach { (infix, expectedAlgorithms) ->
            val file = singleFixture(infix, "_publickey.gpg")
            val packetList = PacketDecoder.decode(file.readBytes())
            val keyPackets = packetList.filterIsInstance<PacketPublicKey>()

            assertEquals(expectedAlgorithms.size, keyPackets.size, "for ${file.name}")
            keyPackets.forEachIndexed { index, keyPacket ->
                assertEquals(expectedAlgorithms[index], keyPacket.algorithm)
                assertTrue(keyPacket is PacketPublicKeyV4)
            }
        }
    }

    @Test
    fun signedMessageStructureTest() {
        val file = messageFixtureOf("ed25519", "signed.gpg")
        val packetList = PacketDecoder.decode(file.readBytes())

        // One-Pass Signature (v3) + Literal Data + Signature (v4).
        assertEquals(3, packetList.size)
        assertEquals(Tag.OnePassSignature, packetList[0].tag)
        assertEquals(Tag.LiteralData, packetList[1].tag)
        assertEquals(Tag.Signature, packetList[2].tag)

        val signaturePacket = packetList[2]
        assertTrue(signaturePacket is PacketSignatureV4)
        assertEquals(4, (signaturePacket as PacketSignatureV4).version)
    }

    @Test
    fun encryptedMessageStructureTest() {
        val file = messageFixtureOf("ed25519", "encrypted.gpg")
        val packetList = PacketDecoder.decode(file.readBytes())

        // PKESK (v3) + v2 SEIPD (AEAD, as emitted by a stock gpg 2.5).
        assertEquals(2, packetList.size)
        assertEquals(Tag.PublicKeyEncryptedSessionKey, packetList[0].tag)
        assertEquals(Tag.SymEncryptedAndIntegrityProtectedData, packetList[1].tag)
    }

    @Test
    fun symmetricallyEncryptedMessageStructureTest() {
        val file = File(fixtureDir, "hello_txt_symmetric_encrypted.gpg")
        val packetList = PacketDecoder.decode(file.readBytes())

        // SKESK (v4) + v1 SEIPD.
        assertEquals(2, packetList.size)
        assertEquals(Tag.SymmetricKeyEncryptedSessionKey, packetList[0].tag)
        assertEquals(Tag.SymEncryptedAndIntegrityProtectedData, packetList[1].tag)
    }

    @Test
    fun secretKeyStructureTest() {
        val file = singleFixture("ed25519", "_secretkey.gpg")
        val packetList = PacketDecoder.decode(file.readBytes())

        val secretKeyPacket = packetList.filterIsInstance<PacketSecretKeyV4>().first()
        assertEquals(4, secretKeyPacket.version)
        // Exported by gpg with an empty passphrase: cleartext secret
        // key material.
        assertEquals(SecretKeyEncryptionType.ClearText, secretKeyPacket.string2keyUsage)
    }
}
